sudo: false
language: ruby
rvm:
  - 2.0.0
before_install: gem install bundler -v 1.12.5
addons:
  code_climate:
    repo_token:
      secure: "NAjO10wrSWlyrTC+hj+4Mk3ORZqr7yoD4Or8HIj7YkpKX4l9neqiaOCmNi34wImpJttEsbH/ICIfqphjp1w7VEdS/HnVcJEv3mO9fJ3uLYXJY9uTlwlotdHQ5xCIpyQQJswRw1ef2kH55ACZOWcfC/Sp7sZ9L/xb/3Gb9o1hC6pH0Kd87gx4X8v/THfynR5tPoXUjWCN1RZDcshdTBqOLIyMBdlueZQ2bmiqPQEtCorixCSF2z0oxBXlNoklkPVGOqPXiER/KFaUmDTupSnWw9CGO/00CA1ErU2pk4LTSQwDTZbMQ6ciIl3JTaM9YtJhaKVw2qrSAEKBFjUVmSlqblwAr/A47MaNxD7B6gWe5aKjt1aPsWddNJDf43SSb4B4yh8FfA++c+ydB3XN1yEgg4eoKrqezIgffzbETGGIrlKkbEVqYzXeS3d8N2Zn/ads7Ie1QQsGaH858r+2Taser/saYqF/KIJwMOIiOAAriGJxIk70hHM5ocJVNVtyJpWOTZ1Tzoqtgayfk3lLLixzenh+HRoOLtXg4lCXOZJ+R78w9NCIG/y5ltJJqW9lXlajJHGlIvdkGKD9Q3MKAuH4UbUw6Ni12T8HigEcf1DdDGahNcL2vUdDeIF+mAGTl0blBiLnjmaj+KsfpwC0LcIVBHeLVPV48r2eld6LaNgFeT4="
# regular test configuration
after_success:
  - bundle exec codeclimate-test-reporter
